name = input("What is your name?")
age = input("How old are you?")
dateofbirth = input("When were you born?")
occupation = input("What is you occupation?")
education = input("Where were you educated?")
networth = input("What is your net worth?")
favouritefood = input("What is your favourite food?")
print("I also like {}!".format(favouritefood)
