import turtle
timmy = turtle.Turtle()
timmy.pensize(5)
timmy.pencolor("red")
timmy.left(90)
timmy.forward(100)
timmy.left(180)
timmy.forward(30)
timmy.right(90)
timmy.forward(25)
timmy.left(180)
timmy.forward(50)
timmy.left(180)
timmy.forward(25)
timmy.left(90)
timmy.forward(70)
timmy.left(90)
timmy.forward(25)
timmy.left(90)
timmy.forward(25)
timmy.left(180)
timmy.forward(25)
timmy.left(90)
timmy.forward(30)
timmy.left(90)
timmy.forward(25)
timmy.left(180)
timmy.forward(100)
timmy.right(90)
timmy.forward(25)
timmy.left(180)
timmy.forward(25)
timmy.left(90)
timmy.forward(75)
timmy.right(90)
timmy.forward(25)
timmy.left(90)
timmy.forward(100)
timmy.left(180)
timmy.forward(100)
timmy.left(90)
timmy.forward(25)
timmy.left(90)
timmy.forward(25)
timmy.right(90)
timmy.forward(30)
timmy.right(90)
timmy.forward(12)
timmy.right(90)
timmy.forward(30)
timmy.left(90)
timmy.forward(13)
timmy.left(90)
timmy.forward(55)
timmy.left(90)
timmy.forward(25)
timmy.right(90)
timmy.forward(15)
timmy.end_fill()
#define pen size
timmy.pensize (5)
 
#define pen color
timmy.pencolor ("Blue")
 
#for outer bigger circle
timmy.begin_fill
timmy.fillcolor ("red")
timmy.penup ()
timmy.goto (50, 100)
timmy.pendown ()
timmy.circle (200)
 
#for eyes
timmy.penup ()
timmy.goto (-50,350)
timmy.pendown ()
timmy.begin_fill ()
timmy.circle (17.5)
timmy.end_fill ()
timmy.penup ()
timmy.goto (150,350)
timmy.pendown ()
timmy.begin_fill ()
timmy.circle (17.5)
timmy.end_fill ()
 
#for nose
timmy.penup ()
timmy.goto (50,350)
timmy.pendown ()
timmy.circle (-70, steps=3)
 
# for smile
timmy.penup ()
timmy.goto (-50, 230)
timmy.pendown ()
timmy.right (90)
timmy.circle (100,180)


